baseURL = 'https://example.org/'
languageCode = 'en-us'
title = "Tina's notes"
theme = 'ananke'

[[menus.main]]
name = "Research"
url = "/research/"
weight = 1

[[menus.main]]
name = "Posts"
url = "/posts/"
weight = 2
